### ISSUE TITLE
Unable to generate proper output with new maps using the pretrained model

### ISSUE THREAD

**Issue by ChintanTrivedi** [zth667/Diverse-Image-Synthesis-from-Semantic-Layout#1]
Getting very different results when trying on new segmentation maps:-

![Untitled presentation (3)](https://user-images.githubusercontent.com/15974320/64338192-c37e7c00-cffe-11e9-9741-4f2c98850e69.png)

Both the outputs are generated on my system using the same pre-trained model. What am I doing wrong? Thanks!

**Comment by zth667** [comment]
Could you please send the new semantic map (without captions) to me?
I've tried testing some uncommon maps based on the left example in your post and they all seem to be working.
![what](https://user-images.githubusercontent.com/26522926/64426054-2136c500-d0e0-11e9-9f76-93cf414600da.png)

**Comment by ChintanTrivedi** [comment]
Here are the three new images I tried-

1) First one is a reshaped image from a cityscapes map I googled online. This one didn't work well. 
![img1](https://user-images.githubusercontent.com/15974320/64426492-44f01000-d0cc-11e9-8117-718a6060ee1f.png)
![2018-01-11-cityscapes](https://user-images.githubusercontent.com/15974320/64426552-779a0880-d0cc-11e9-84ce-9b45ca67904b.png)

2) I created a custom map in paint, it worked well.
![img2](https://user-images.githubusercontent.com/15974320/64426493-44f01000-d0cc-11e9-9d40-2db8c6c1512d.png)
![00100086 (copy)](https://user-images.githubusercontent.com/15974320/64426596-97c9c780-d0cc-11e9-8fd7-e30f4f408dc9.png)

3) This last one is the semantic map I obtained from the PSPNet segmentation model. This one again didn't work too well.
![gta2res_seg_blended](https://user-images.githubusercontent.com/15974320/64426751-0f97f200-d0cd-11e9-87c9-0a886260a8a9.jpg)
![gta2res_seg](https://user-images.githubusercontent.com/15974320/64426683-d9f30900-d0cc-11e9-9fdd-7aa7a68ff60f.jpg)
![gta2res_segres](https://user-images.githubusercontent.com/15974320/64426697-e4150780-d0cc-11e9-8a94-32b0a28558e0.png)

**Comment by zth667** [comment]
Thanks for sharing the maps. 
The reason of the abnormality seems to be that both maps are quite lossy (which could be a result of using the jpeg format or other compression methods). To easily transfer the image into one-hot vectors, the project requires every pixel of the input map to be exactly in the 19-color palette (which is saved in datasets/cityscapes.json) except a few unlabeled pixels, whereas a lossy map could contain lots of pixels that slightly differ from the correct colors. 
A simple solution could be to set each pixel to its nearest color in the palette. For example, one can use the following code
```
import numpy as np
from scipy.misc import imread,imresize,imsave
import os,sys
from scipy.spatial.distance import cdist
#The 19 colors
bins = np.array([[128,64,128],[244,35,232],[70,70,70],[102,102,156],[190,153,153],[153,153,153],[250,170,30],[220,220,0],[107,142,35],[152,251,152],[70,130,180],[220,20,60],[255,0,0],[0,0,142],[0,0,70],[0,60,100],[0,80,100],[0,0,230],[119,11,32]])
#the input image name
filename = sys.argv[1]
im = imread(filename)
im = im[:,:,:3]
im = imresize(im,(256,512))
for i in range(256):
     for j in range(512):
         idx = np.argsort(cdist([im[i,j]],bins,'euclidean')[0])[0]
         im[i,j] = bins[idx]
imsave(filename[:-4]+"_recovered.png",im)
```
However, the method is not perfect since a lossy pixel could sometimes vary hugely from the original one. But it could at least provide rational results. The best way is still using the original lossless maps.

**Comment by ChintanTrivedi** [comment]
Thanks, that worked out! You're right, resizing the image in an image editing software was causing these interpolation colors to show up that I completely missed. Appreciate the help, looking forward to reading the paper next :)

![img3_recovered](https://user-images.githubusercontent.com/15974320/64442126-e5eec300-d0ec-11e9-9bf8-0e96962a3d5e.png)
